export const mockData = [
  {
    brands: {
      "-MUNuxd-1azwBHl-1v5E": {
        advertiser: "-MjnPMth_2LRN6_1Dhwj",
        amount: 50,
        commission: 2001,
        influencers: 250,
        influencersCommission: 26565,
        soldProductsNumber: 30,
        agentsCommissions: {
          "-MLOI__mVOzrdubyMyqu": {
            commissionAgent: "0.1%",
            commissionInfs: "6.9%",
          },
          "-MOg7b5YSDgNH0rhGMlt": {
            commissionAgent: "1.40%",
            commissionInfs: "5.60%",
          },
          "-MmrmzmI8TtRZqUG0j5N": {
            commissionAgent: "2.10%",
            commissionInfs: "4.90%",
          },
        },
        allCommissions: {
          basicCommission: "10.00%",
          generalCommission: "7%",
        },
        calcCommissionManually: false,
        categ: [
          "-MVVjqB0bnq2XEnBltNY",
          "-MVVjqB0bnq2XEnBltNZ",
          "-M_CURbKPKWUOChBEKuA",
          "-MVVjqB1U0DvXaMu7sbk",
          "-MkDF5C53fiZ6P_pC57x",
          "-MVVjqB-K4ly_OF7uvj-",
          "-MYdiQ0q_m-iQEgXv_gb",
          "-MVVjqArILS7OyGutYuC",
        ],
        categories: {
          Accessoires: 1,
          Bijoux: 1,
          Chaussures: 1,
          Enfants: 1,
          "Maison & jardin ": 1,
          "Mode femme": 1,
          "Mode homme": 1,
          Sport: 1,
        },
        "categories-en": {
          Accessories: 1,
          "House & garden": 1,
          Jewelry: 1,
          Kids: 1,
          "Men' fashion": 1,
          Shoes: 1,
          Sport: 1,
          "Women' fashion": 1,
        },
        commissions: {
          "commission générale": "7%",
        },
        "commissions-en": {
          "general commission": "7%",
        },
        createdAt: "1614252071",
        defaultTrackingDomain: false,
        description:
          "Avec KIABI, le prix n'a jamais été une excuse pour ne pas être à la mode",
        "description-en":
          "With KIABI, price has never been an excuse for not being fashionable",
        displayName: "kiabi",
        hasAdvertiser: true,
        hasGifting: false,
        href: "https://www.kiabi.com/",
        isPrivateAndroidApp: false,
        isPrivateCampaign: false,
        isPrivateIOSApp: false,
        is_independent: false,
        key: "-MUNuxd-1azwBHl-1v5E",
        localisation: "FR",
        name: "kiabi",
        offerId: 23,
        pic: "https://firebasestorage.googleapis.com/v0/b/shopmyinfluens.appspot.com/o/shopmyinfluens%2FBrands%2Fclassic_brands%2Fkiabi_512.jpg?alt=media",
        premium: true,
        private: false,
        privateAndroidApp: false,
        privateIOSApp: false,
        region: "worldwide",
        score: 11916,
        src_premium:
          "https://firebasestorage.googleapis.com/v0/b/shopmyinfluens.appspot.com/o/shopmyinfluens%2FBrands%2Fpremium_brands%2Fkiabi-z.jpg?alt=media&token=42dfd2a7-74d6-48ae-aadd-1c5876edfe1e",
      },
      "-MYyHQuGDhg-HqFXDB4O": {
        advertiser: "-MjnQDnuMniHT-l1HxZv",
        amount: 20,
        commission: 1500,
        influencers: 652655,
        influencersCommission: 2555,
        soldProductsNumber: 266,
        agentsCommissions: {
          "-MLOI__mVOzrdubyMyqu": {
            commissionAgent: "0%",
            commissionInfs: "4%",
          },
          "-MOg7b5YSDgNH0rhGMlt": {
            commissionAgent: "0.80%",
            commissionInfs: "3.20%",
          },
          "-MmrmzmI8TtRZqUG0j5N": {
            commissionAgent: "1.20%",
            commissionInfs: "2.80%",
          },
        },
        allCommissions: {
          basicCommission: "6%",
          generalCommission: "4%",
          optionalCommissions: [
            {
              commissionEn: "new clients commission ",
              commissionFr: "commission nouveaux clients ",
              commissionValue: "6%",
            },
          ],
        },
        calcCommissionManually: false,
        categ: [
          "-MVVjqB0bnq2XEnBltNY",
          "-MVVjqB-K4ly_OF7uvj-",
          "-MVVjqB0bnq2XEnBltNZ",
          "-M_CURbKPKWUOChBEKuA",
          "-MVVjqArILS7OyGutYuC",
          "-MkDHckmpYdKzYsm45Te",
        ],
        categories: {
          Accessoires: 1,
          Chaussures: 1,
          Enfants: 1,
          Lingerie: 1,
          "Mode femme": 1,
          "Mode homme": 1,
        },
        "categories-en": {
          Accessories: 1,
          Kids: 1,
          Lingerie: 1,
          "Men' fashion": 1,
          Shoes: 1,
          "Women' fashion": 1,
        },
        commissions: {
          "Anciens clients": "6",
          "commission générale": "4%",
          "commission nouveaux clients ": "6%",
        },
        "commissions-en": {
          "general commission": "4%",
          "new clients commission ": "6%",
          "old customers": "6",
        },
        createdAt: "1618920503",
        creatorUser: "iLNdBoQKdkW7J9ruzOGFQt3Rcbm2",
        creatorUserEmail: "gemo@influens.fr",
        defaultTrackingDomain: false,
        description:
          "Gémo est, depuis 20 ans, reconnu comme un acteur référent sur le textile et la chaussure.",
        "description-en":
          "Gémo has been recognized for 20 years as a leading player in textiles and footwear.",
        displayName: "gemo",
        hasAdvertiser: true,
        hasGifting: false,
        href: "https://www.gemo.fr/",
        isPrivateAndroidApp: true,
        isPrivateCampaign: false,
        isPrivateIOSApp: true,
        key: "-MYyHQuGDhg-HqFXDB4O",
        localisation: "FR",
        name: "gemo",
        offerId: 1368,
        pic: "https://firebasestorage.googleapis.com/v0/b/shopmyinfluens.appspot.com/o/shopmyinfluens%2FBrands%2Fclassic_brands%2FG%C3%A9mo.png?alt=media",
        premium: false,
        private: false,
        privateAndroidApp: false,
        privateIOSApp: false,
        score: 516,
        siret: "000",
      },
      "-MiX1N0oKYU8GOOo_eG0": {
        advertiser: "-MjnRZxmfPWXUkMZpu0i",
        amount: 35,
        commission: 1655,
        influencers: 988,
        influencersCommission: 255898,
        soldProductsNumber: 924,
        agentsCommissions: {
          "-MLOI__mVOzrdubyMyqu": {
            commissionAgent: "0.1%",
            commissionInfs: "6.9%",
          },
          "-MOg7b5YSDgNH0rhGMlt": {
            commissionAgent: "1.40%",
            commissionInfs: "5.60%",
          },
          "-MmrmzmI8TtRZqUG0j5N": {
            commissionAgent: "2.10%",
            commissionInfs: "4.90%",
          },
        },
        allCommissions: {
          basicCommission: "8%",
          generalCommission: "7%",
          optionalCommissions: [
            {
              commissionEn: "New clients ",
              commissionFr: "Nouveaux clients",
              commissionValue: "10%",
            },
          ],
        },
        calcCommissionManually: false,
        categ: [
          "-MVVjqB0bnq2XEnBltNY",
          "-MVVjqArILS7OyGutYuC",
          "-MVVjqB-K4ly_OF7uvj-",
        ],
        categories: {
          Accessoires: 1,
          Chaussures: 1,
          "Mode femme": 1,
        },
        "categories-en": {
          Accessories: 1,
          Shoes: 1,
          "Women' fashion": 1,
        },
        commissions: {
          "Commission nouveaux clients": "6%",
          "Nouveaux clients": "10%",
          "commission générale": "7%",
        },
        "commissions-en": {
          "New clients ": "10%",
          "New clients commission": "6%",
          "general commission": "7%",
        },
        createdAt: 1630511130,
        creatorUser: "dvZdramprTffsjK5Eq9vu5wsAXE2",
        defaultTrackingDomain: false,
        description:
          "Depuis 1984 camaieu propose une mode accessible, facile à porter, et déclinée dans un large colorama destinés pour les femmes.",
        "description-en":
          "Since 1984 camaïeu offers accessible fashion, easy to wear, and declined in a large colorama intended for women",
        displayName: "Camaieu",
        hasAdvertiser: true,
        hasGifting: false,
        href: "https://www.camaieu.fr",
        isPrivateAndroidApp: false,
        isPrivateCampaign: false,
        isPrivateIOSAppValue: false,
        key: "-MiX1N0oKYU8GOOo_eG0",
        localisation: "FR",
        name: "camaieu",
        offerId: 1514,
        pic: "https://firebasestorage.googleapis.com/v0/b/shopmyinfluens.appspot.com/o/shopmyinfluens%2FBrands%2Fclassic_brands%2Fcamaieu-2.jpg?alt=media",
        premium: false,
        private: false,
        privateAndroidApp: false,
        privateIOSApp: false,
        role: "admin",
        score: 235,
        siret: "123",
      },
      "-MUNuxd5C80y6z71tFCl": {
        advertiser: "-MjnPMth_2LRN6_1Dhwj",
        amount: 36,
        commission: 575757,
        influencers: 89999,
        influencersCommission: 98555,
        soldProductsNumber: 9887,
        agencyCommission: "3%",
        agentsCommissions: {
          "-MLOI__mVOzrdubyMyqu": {
            commissionAgent: "0.1%",
            commissionInfs: "6.9%",
          },
          "-MOg7b5YSDgNH0rhGMlt": {
            commissionAgent: "1.40%",
            commissionInfs: "5.60%",
          },
          "-MmrmzmI8TtRZqUG0j5N": {
            commissionAgent: "2.10%",
            commissionInfs: "4.90%",
          },
        },
        allCommissions: {
          agencyCommission: "3%",
          basicCommission: "10%",
          generalCommission: "7%",
        },
        calcCommissionManually: false,
        categ: ["-MVVjqB-K4ly_OF7uviz", "-MYdjMr_QT_fOrEoGa23"],
        categories: {
          Beauté: 1,
          "Parfums & Bougies": 1,
        },
        "categories-en": {
          Beauty: 1,
          "Perfumes & Candles": 1,
        },
        commissions: {
          "commission générale": "7%",
        },
        "commissions-en": {
          "general commission": "7%",
        },
        createdAt: "1614252071",
        defaultTrackingDomain: false,
        description: "Le meilleur de la beauté dans un seul endroit.",
        "description-en": "The best of beauty in one place.",
        displayName: "sephora FR",
        hasAdvertiser: true,
        hasGifting: false,
        href: "https://www.sephora.fr/",
        isPrivateAndroidApp: false,
        isPrivateCampaign: false,
        isPrivateIOSApp: false,
        is_independent: false,
        key: "-MUNuxd5C80y6z71tFCl",
        localisation: "FR",
        name: "sephorafr",
        offerId: 1066,
        pic: "https://firebasestorage.googleapis.com/v0/b/shopmyinfluens.appspot.com/o/shopmyinfluens%2FBrands%2Fclassic_brands%2Fsephora.jpg?alt=media",
        premium: true,
        private: false,
        privateAndroidApp: false,
        privateIOSApp: false,
        region: "worldwide",
        score: 594,
        src_premium:
          "https://firebasestorage.googleapis.com/v0/b/shopmyinfluens.appspot.com/o/shopmyinfluens%2FBrands%2Fpremium_brands%2FSephora-z.jpg?alt=media&token=28b12457-d7e1-4fda-8e3a-38e839cbeec1",
      },
    },
  },
];
